Algoritmo "Funçoes Extras Portugol"

Var
site : Caractere

Inicio
site <- "Pokemon.com"
//Compr (site) - Mostra o comprimento da variável
//Copia (site, 2 - Letra que Começa a contar, 5 - Quantas Casas vai mostrar)
// Maiusc (site) - Deixa tudo Maisculo
// Minusc (site) - Deixa tudo Minusculo
// Pos ("Video" , site) - Retorna posição da palavra na string
// ASC (site) - Retorna código de cada letra.
// Carac (site) - Retorna a letra de cada código.

Fimalgoritmo