Algoritmo "69"

Var
   paT, razao, c, soma: inteiro

Inicio

   Escreva ("Me diga o primeiro valor da progressão aritimética: ")
   Leia (paT)

   Escreva ("Me diga a razão da progressão aritimética: ")
   Leia (razao)

   Para c <- 1 até 10 faca
      Escreval (paT)
      paT <- paT + razao
      soma <- soma + paT
   FimPara
   
   Escreval ("A soma de todos os valores da progressão aritimética é de: ", soma)
   






Fimalgoritmo