Algoritmo "44"

Var
   valorFinal, valorInicial, incremento: inteiro

Inicio
   Escreva ("Me diga o valor Inicial: ")
   Leia (valorInicial)
   Escreva ("Me diga o valor Final: ")
   Leia (valorFinal)
   Escreva ("Me diga o incremento: ")
   Leia (incremento)

   Enquanto ( valorInicial <= valorFinal) faca
         Escreval (" " , valorInicial)
         valorInicial <- valorInicial + incremento
   Fimenquanto
   Escreval ("Acabou!")


Fimalgoritmo