Algoritmo "32"

Var
   sorteado, escolhaN, numA : inteiro


Inicio
      aleatorio 1,5
      Leia (sorteado)
      aleatorio off
      limpatela()
      Escreva ("Advinhe o número sorteado de 1 a 5: ")
      Leia (escolhaN)
      
      Se (escolhaN = sorteado) entao
         Escreva ("Parabéns, você acertou!")
      Senao
         Escreva ("Você errou, tente novamente.")
      Fimse

      

Fimalgoritmo