Algoritmo "26"

Var
   a, b, maior : inteiro


Inicio
   Escreva ("Valor primeiro número: ")
   Leia (a)
   Escreva ("Valor segundo número: ")
   Leia (b)

   Se (a > b) entao
      Escreval ("O primeiro valor é maior.")
   Senao
      Se (a = b) entao
         Escreval ("Os dois valores são iguais.")
      Senao
         Se ( a < b) entao
            Escreval ("O segundo valor é maior.")
         Fimse
      Fimse
   Fimse
   
Fimalgoritmo