Algoritmo "10"

Var
l, h, a, qT: real


Inicio
Escreva ("Qual a altura da parede em metros: ")
leia (h)
Escreva ("Qual a largura da parede em metros: ")
leia (l)
a <- l * h
qt <- a/2
Escreval ("=================================")
Escreval ("A área da parede é de: " , a , " metros.")
Escreval ("A quantia de tinta necessária é de : " , qT , " litros.")
Escreval ("=================================")


Fimalgoritmo