Algoritmo "8"

Var
mm, dm, cm, m, dam, hm, km : real


Inicio
Escreva ("Me diga quantia numérica em metros: ")
Leia (m)
mm <- m * 1000
cm <- m * 100
dm <- m * 10
dam <- m / 10
hm <- m / 100
km <- m / 1000
Escreval (m ," Metros são equivalentes a: ")
Escreval (mm ," Milímetros.")
Escreval (cm ," Centímetros.")
Escreval (dm ," Decímetros")
Escreval (dam ," Decâmetros.")
Escreval (hm ," Hectômetros.")
Escreval (km ," Quilômetros.")



Fimalgoritmo